export const images = {
  bag: require('../assets/images/bag.png'),
  search: require('../assets/images/Search.png'),
  arrow: require('../assets/images/arrow.png'),
  card: require('../assets/images/Card.png'),
  fav: require('../assets/images/fav.png'),
  unFav: require('../assets/images/unFav.png'),
  product: require('../assets/images/product.png'),
  add: require('../assets/images/addicon.png'),
  home: require('../assets/images/home.png'),
  category: require('../assets/images/Category.png'),
  favourite: require('../assets/images/Stroke.png'),
  menu: require('../assets/images/coolicon.png'),
  star: require('../assets/images/Star.png'),
  halfstar: require('../assets/images/HalfStar.png'),
  heart: require('../assets/images/Heart.png'),
  back: require('../assets/images/Back.png'),
  plus: require('../assets/images/Plus.png'),
  minus: require('../assets/images/Minus.png'),
};
